//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.5.5
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>About</summary>
	[PublishedModel("about")]
	public partial class About : PublishedContentModel, INavigation
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.5")]
		public new const string ModelTypeAlias = "about";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.5")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.5")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.5")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<About, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public About(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// about Banner
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.5")]
		[ImplementPropertyType("aboutBanner")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent AboutBanner => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("aboutBanner");

		///<summary>
		/// 内容图片
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.5")]
		[ImplementPropertyType("aboutContentImage")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent AboutContentImage => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("aboutContentImage");

		///<summary>
		/// 内容主题
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.5")]
		[ImplementPropertyType("aboutContentText")]
		public global::System.Web.IHtmlString AboutContentText => this.Value<global::System.Web.IHtmlString>("aboutContentText");

		///<summary>
		/// 内容标题
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.5")]
		[ImplementPropertyType("aboutContentTitle")]
		public string AboutContentTitle => this.Value<string>("aboutContentTitle");

		///<summary>
		/// 页面标题
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.5")]
		[ImplementPropertyType("aboutTitle")]
		public string AboutTitle => this.Value<string>("aboutTitle");

		///<summary>
		/// 添加导航菜单: 如有需求可以在此添加导航
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.5")]
		[ImplementPropertyType("addToNav")]
		public bool AddToNav => global::Umbraco.Web.PublishedModels.Navigation.GetAddToNav(this);
	}
}
