//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.5.5
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Meal</summary>
	[PublishedModel("meal")]
	public partial class Meal : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.5")]
		public new const string ModelTypeAlias = "meal";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.5")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.5")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.5")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Meal, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public Meal(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// 餐品图片
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.5")]
		[ImplementPropertyType("mealImage")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent MealImage => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("mealImage");

		///<summary>
		/// 餐品名称
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.5")]
		[ImplementPropertyType("mealName")]
		public string MealName => this.Value<string>("mealName");

		///<summary>
		/// 餐品价格
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.5")]
		[ImplementPropertyType("mealPrice")]
		public string MealPrice => this.Value<string>("mealPrice");

		///<summary>
		/// 商品标签
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.5")]
		[ImplementPropertyType("mealTags")]
		public global::System.Collections.Generic.IEnumerable<string> MealTags => this.Value<global::System.Collections.Generic.IEnumerable<string>>("mealTags");

		///<summary>
		/// 目录类型
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.5")]
		[ImplementPropertyType("menuType")]
		public string MenuType => this.Value<string>("menuType");
	}
}
